### PR TITLE
Added QOTD Plugin

### PR DESCRIPTION
**Pull request by merkidemis**
Added new slash command plugin qotd.

### CODE REVIEW

**Comment by gtracy** [comment]
@merkidemis Any thoughts on the above?

**Comment by merkidemis** [comment]
Correct, it should be request.quotes[0].quote. 

For additional interest, though I'd have to see if they were possible, I'd use the category to change the bot icon, change the font color, or insert an emoji. I'd also attach the associated image to the feed as well, though it would be cool if it could be set as a Slack or desktop background. Additionally, using the other queries available on that site I would like to be able to specify particular categories per user, or by the admin for certain situations like motivation when we're getting close to the end of the quarter, or inspire during a slow period.

**Comment by merkidemis** [comment]
For a quality increase I'd split out that complex line on the .s to individual assignments so I could more accurately detect where data was missing, say if the JSON schema changed.

**Comment by gtracy** [comment]
Let me know when you submit a new pull request with a functioning plugin. I'll take a look again.

**Comment by merkidemis** [comment]
I've been unable to test this. 

- Slack-Stuart will not compile on Windows 10
- it compiles under Linux (Ubuntu 15.10), but fails on startup with an error in your markov plugin:
ERROR - Caught Error ReferenceError: Map is not defined
ERROR - Stack ReferenceError: Map is not defined
- I cannot run it locally anyway as all incoming http requests are blocked by my ISP
- It compiles on heroku.com, but throws an Application Error

All these have been attempted on Node 0.10.36 and Python 2.7.

**Pull request closed without merging**
